/**
 * Generic branded PDF for mobile/web report exports (PDFKit).
 */

const THEME = '#0A74DA';

function safeText(value) {
	if (value == null) return '—';
	if (typeof value === 'number' && Number.isFinite(value)) {
		return Number.isInteger(value) ? String(value) : value.toFixed(2);
	}
	return String(value);
}

function humanizeKey(key) {
	return String(key || '')
		.replace(/_/g, ' ')
		.replace(/([a-z])([A-Z])/g, '$1 $2')
		.replace(/\b\w/g, (c) => c.toUpperCase());
}

/**
 * @param {{
 *   title?: string,
 *   companyName?: string,
 *   dateRangeLabel?: string,
 *   cards?: Array<{ label?: string, value?: unknown }>,
 *   rows?: Array<Record<string, unknown>>,
 * }} payload
 * @returns {Promise<Buffer>}
 */
export async function buildReportPdfBuffer(payload = {}) {
	const PDFDocument = (await import('pdfkit')).default;
	const title = String(payload.title || 'Report').trim() || 'Report';
	const companyName = String(payload.companyName || 'Shopynn').trim() || 'Shopynn';
	const dateRangeLabel = String(payload.dateRangeLabel || 'All time').trim() || 'All time';
	const cards = Array.isArray(payload.cards) ? payload.cards : [];
	const rows = Array.isArray(payload.rows) ? payload.rows : [];
	const exportedAt = new Date().toLocaleString('en-GB', {
		year: 'numeric',
		month: 'short',
		day: 'numeric',
		hour: '2-digit',
		minute: '2-digit',
	});

	const columns =
		rows.length > 0
			? Object.keys(rows[0]).filter((k) => k !== '_raw' && k !== 'id')
			: [];

	return new Promise((resolve, reject) => {
		const doc = new PDFDocument({ margin: 48, size: 'A4' });
		const chunks = [];
		doc.on('data', (chunk) => chunks.push(chunk));
		doc.on('end', () => resolve(Buffer.concat(chunks)));
		doc.on('error', reject);

		doc.fillColor(THEME).fontSize(18).text(companyName, { align: 'left' });
		doc.fillColor('#64748b').fontSize(9).text('Inventory · Orders · Sales · Reports');
		doc.moveDown(0.8);

		doc.fillColor(THEME).fontSize(16).text(title);
		doc.fillColor('#334155').fontSize(10);
		doc.text(`Period: ${dateRangeLabel}`);
		doc.text(`Exported: ${exportedAt}`);
		doc.text(`Rows: ${rows.length}`);
		doc.moveDown();

		if (cards.length) {
			doc.fillColor(THEME).fontSize(12).text('Summary');
			doc.moveDown(0.4);
			cards.forEach((card) => {
				doc.fillColor('#64748b').fontSize(9).text(String(card.label || 'Metric'));
				doc.fillColor('#0f172a').fontSize(12).text(safeText(card.value));
				doc.moveDown(0.35);
			});
			doc.moveDown(0.4);
		}

		if (columns.length && rows.length) {
			doc.fillColor(THEME).fontSize(12).text('Details');
			doc.moveDown(0.3);

			const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
			const colWidth = pageWidth / columns.length;
			const startX = doc.page.margins.left;

			const drawHeader = (y) => {
				doc.rect(startX, y, pageWidth, 22).fill(THEME);
				doc.fillColor('#ffffff').fontSize(8);
				columns.forEach((key, i) => {
					doc.text(humanizeKey(key), startX + i * colWidth + 4, y + 7, {
						width: colWidth - 8,
						ellipsis: true,
					});
				});
				return y + 26;
			};

			let y = drawHeader(doc.y);
			doc.fillColor('#0f172a').fontSize(8);

			rows.forEach((row, rowIndex) => {
				if (y > doc.page.height - 72) {
					doc.addPage();
					y = drawHeader(48);
					doc.fillColor('#0f172a').fontSize(8);
				}
				if (rowIndex % 2 === 1) {
					doc.rect(startX, y - 3, pageWidth, 16).fill('#f1f5f9');
					doc.fillColor('#0f172a');
				}
				columns.forEach((key, i) => {
					doc.text(safeText(row[key]), startX + i * colWidth + 4, y, {
						width: colWidth - 8,
						ellipsis: true,
					});
				});
				y += 16;
			});
		} else if (!rows.length) {
			doc.fillColor('#64748b').fontSize(10).text('No detail rows for this period.');
		}

		doc.moveDown(2);
		doc.fillColor('#94a3b8').fontSize(8).text('Generated by Shopynn', { align: 'center' });

		doc.end();
	});
}
