import express from "express";
import auth from "../middleware/auth.js";
import requireActiveSubscription from "../middleware/requireActiveSubscription.js";
const router = express.Router();

import userroutes from "./userroutes.js";
import imageroutes from "./imageroutes.js";
import productroutes from "./productroutes.js";
import purchaseroutes from "./purchaseroutes.js";
import warehouseroutes from "./warehouseroutes.js";
import saleroutes from "./saleroutes.js";
import adjustmentroutes from "./adjustmentroutes.js";
import transferroutes from "./transferroutes.js";
import inventoryroutes from "./inventoryroutes.js";
import customerroutes from "./customerroutes.js";
import categoryroutes from "./categoryroutes.js";
import expenseroutes from "./expenseroutes.js";
import locationroutes from "./locationroutes.js";
import supplierroutes from "./supplierroutes.js";
import mailroutes from "./mailroutes.js";
import transactionroutes from "./transactionroutes.js";
import dashboardroutes from "./dashboardroutes.js";
import stockcountroutes from "./stockcountroutes.js";
import returnroutes from "./returnroutes.js";
import paymentroutes from "./paymentroutes.js";
import industryroutes from "./industryroutes.js";
import { paymentWebhook } from "../controllers/payment.js";
import notificationroutes from "./notificationroutes.js";
import subscriptionroutes from "./subscriptionroutes.js";
import tenantroutes from "./tenantroutes.js";
import merchantroutes from "./merchantroutes.js";
import appVersionRoutes from "./appVersionRoutes.js";
import roleroutes from "./roleroutes.js";
import permissionroutes from "./permissionroutes.js";
import userManagementRoutes from "./userManagementRoutes.js";
import auditLogRoutes from "./auditLogRoutes.js";
import orderroutes from "./orderroutes.js";
import customerprofileroutes from "./customerprofileroutes.js";
import storeorderroutes from "./storeorderroutes.js";
import publicroutes from "./publicroutes.js";
import newsletterroutes from "./newsletterroutes.js";
import contactRequestroutes from "./contactRequestroutes.js";
import siteChatroutes from "./siteChatroutes.js";
import billingroutes from "./billingroutes.js";
import broadcastroutes from "./broadcastroutes.js";

router.use('/users', userroutes);
router.use("/public", publicroutes);
router.use("/app-versions", appVersionRoutes);
router.use("/roles", auth, requireActiveSubscription, roleroutes);
router.use("/permissions", auth, requireActiveSubscription, permissionroutes);
router.use("/user-management", auth, requireActiveSubscription, userManagementRoutes);
router.use("/audit-logs", auth, requireActiveSubscription, auditLogRoutes);
router.use("/dashboard", auth, requireActiveSubscription, dashboardroutes);
router.use('/images', imageroutes);
router.use("/products", auth, requireActiveSubscription, productroutes);
router.use("/purchases", auth, requireActiveSubscription, purchaseroutes);
router.use("/warehouses", auth, requireActiveSubscription, warehouseroutes);
router.use("/sales", auth, requireActiveSubscription, saleroutes);
router.use("/adjustments", auth, requireActiveSubscription, adjustmentroutes);
router.use("/transfers", auth, requireActiveSubscription, transferroutes);
router.use("/inventories", auth, requireActiveSubscription, inventoryroutes);
router.use("/customers", auth, requireActiveSubscription, customerroutes);
router.use("/categories", auth, requireActiveSubscription, categoryroutes);
router.use("/expenses", auth, requireActiveSubscription, expenseroutes);
router.use("/locations", auth, requireActiveSubscription, locationroutes);
router.use("/suppliers", auth, requireActiveSubscription, supplierroutes);
router.use("/emails", auth, requireActiveSubscription, mailroutes);
router.use("/transactions", auth, requireActiveSubscription, transactionroutes);
router.use("/stock-counts", auth, requireActiveSubscription, stockcountroutes);
router.use("/returns", auth, requireActiveSubscription, returnroutes);
router.use("/orders", auth, requireActiveSubscription, orderroutes);
router.use("/customer-profiles", auth, requireActiveSubscription, customerprofileroutes);
router.use("/store-orders", auth, requireActiveSubscription, storeorderroutes);
router.post("/payments/webhook", express.raw({ type: "application/json" }), paymentWebhook);
router.use("/payments", auth, paymentroutes); //requireActiveSubscription
router.use("/notifications", auth, requireActiveSubscription, notificationroutes);
router.use("/subscriptions", auth, subscriptionroutes);
router.use("/tenants", tenantroutes);
router.use("/merchants", merchantroutes);
router.use("/billing", billingroutes);
router.use("/industries", industryroutes);
router.use("/newsletter", newsletterroutes);
router.use("/broadcasts", broadcastroutes);
router.use("/contact-requests", contactRequestroutes);
router.use("/site-chats", siteChatroutes);

export default router;