/**
 * Ready-made staff roles created for every shop. Starter shops can assign them;
 * editing roles (and creating custom ones) needs the Business plan.
 * Keep in sync with migrations/20261010_default_staff_roles.sql.
 */
const CASHIER_PERMISSION_CODES = [
    "dashboard.view",
    "profile.view",
    "profile.update",
    "products.view",
    "products.by_category.view",
    "inventory.view",
    "categories.view",
    "customers.view",
    "customers.create",
    "customers.details.view",
    "sales.view",
    "sales.create",
    "sales.details.view",
    "sales.share_receipt",
    "sales.pending.view",
    "sales.pending.retry",
    "returns.view",
    "returns.create",
    "returns.details.view",
];

const MANAGER_PERMISSION_CODES = [
    ...CASHIER_PERMISSION_CODES,
    "sales.view_all",
    "sales.by_date.view",
    "sales.daily_summary.view",
    "sales.return.create",
    "products.create",
    "products.update",
    "products.update_images",
    "products.change_price",
    "products.toggle_status",
    "products.transactions.view",
    "categories.create",
    "categories.update",
    "customers.update",
    "customers.sales.view",
    "customers.payments.view",
    "purchases.view",
    "purchases.view_all",
    "purchases.create",
    "purchases.details.view",
    "suppliers.view",
    "suppliers.create",
    "suppliers.update",
    "suppliers.details.view",
    "suppliers.purchases.view",
    "expenses.view",
    "expenses.create",
    "expenses.details.view",
    "inventory.low_stock.view",
    "inventory.reorder.view",
    "inventory.expiring.view",
    "adjustments.view",
    "adjustments.create",
    "adjustments.details.view",
    "stock_counts.view",
    "stock_counts.create",
    "stock_counts.details.view",
    "transfers.view",
    "transfers.create",
    "transfers.receive",
    "transfers.details.view",
    "reports.view",
    "payments.view",
    "payments.initiate",
];

export const DEFAULT_STAFF_ROLES = [
    { name: "Manager", description: "Runs the shop day to day: stock, purchases, suppliers, expenses and reports.", permissionCodes: MANAGER_PERMISSION_CODES },
    { name: "Cashier", description: "Sells at the counter and serves customers.", permissionCodes: CASHIER_PERMISSION_CODES },
];
